jobs:
  - job: Deploy

    pool:
      ${{ if eq(variables['vmImage'], '') }}:
        name: $(poolName)
      ${{ if eq(variables['poolName'], '') }}:
        vmImage: $(vmImage)

    steps:
      #Solo se ejecutaran las siguientes tareas cuando se use un self-hosted agent pool
      - task: DownloadBuildArtifacts@0
        condition: and(eq(variables['vmImage'], ''), eq(variables['deployResourceGroup'], 'true'))
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'Artifacts'
          downloadPath: $(System.ArtifactsDirectory)

      - task: AzureCLI@2
        displayName: 'Desplegar resource group'
        condition: and(eq(variables['vmImage'], ''), eq(variables['deployResourceGroup'], 'true'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create -l $(location) --template-file '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(System.ArtifactsDirectory)/Artifacts/$(deployRepo)/${{ parameters.parametersFile }}' --what-if

      - task: AzureCLI@2
        displayName: 'Desplegar recurso'
        condition: and(eq(variables['vmImage'], ''), eq(variables['deployResourceGroup'], 'false'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create -g '$(resourceGroupName)' --template-file '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(System.ArtifactsDirectory)/Artifacts/$(deployRepo)/${{ parameters.parametersFile }}' --what-if


      #Se ejecutaran las siguientes tareas cuando se use un microsoft-hosted agent pool
      - checkout: ModulesRepo

      - task: AzureCLI@2
        displayName: 'Desplegar resource group'
        condition: and(eq(variables['poolName'], ''), eq(variables['deployResourceGroup'], 'true'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create -l $(location) --template-file '${{ parameters.templateFile }}' --parameters '${{ parameters.parametersFile }}' --what-if

      - task: AzureCLI@2
        displayName: 'Desplegar recurso'
        condition: and(eq(variables['poolName'], ''), eq(variables['deployResourceGroup'], 'false'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create -g '$(resourceGroupName)' --template-file '${{ parameters.templateFile }}' --parameters '${{ parameters.parametersFile }}' --what-if






    # - task: AzureResourceManagerTemplateDeployment@3
    #   inputs:
    #     deploymentScope: 'Subscription'
    #     azureResourceManagerConnection: 'emguzman-subscription'
    #     subscriptionId: '72d501de-5778-4b23-8a81-33abfd22d159'
    #     location: 'Central US'
    #     templateLocation: 'Linked artifact'
    #     csmFile: '$(System.ArtifactsDirectory)/Artifacts/modules/resources/resource-group/main.bicep'
    #     csmParametersFile: '$(System.ArtifactsDirectory)/Artifacts/deployments/rg-networking.bicepparam'
    #     deploymentMode: 'Validation'
