jobs:
  - job: Validate

    pool:
      ${{ if eq(variables['vmImage'], '') }}:
        name: $(poolName)
      ${{ if eq(variables['poolName'], '') }}:
        vmImage: $(vmImage)

    steps:
      #Solo se ejecutaran las siguientes tareas cuando se use un self-hosted agent pool
      - task: DownloadBuildArtifacts@0
        condition: eq(variables['vmImage'], '')
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'Artifacts'
          downloadPath: $(System.ArtifactsDirectory)

      - task: AzureCLI@2
        displayName: 'Desplegar resource group'
        condition: and(eq(variables['vmImage'], ''), eq(variables['deployResourceGroup'], 'true'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account set --subscription '${{ parameters.subscriptionName }}'
            deploymentName='azureDeployment'$(date +"%d-%b-%Y")
            az deployment sub create -n $deploymentName -l $(location) --template-file '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.parametersFile }}' --what-if

      - task: AzureCLI@2
        displayName: 'Desplegar recurso'
        condition: and(eq(variables['vmImage'], ''), eq(variables['deployResourceGroup'], 'false'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account set --subscription '${{ parameters.subscriptionName }}'
            deploymentName='azureDeployment'$(date +"%d-%b-%Y")
            az deployment group create -n $deploymentName -g '${{ parameters.resourceGroupName }}' --template-file '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(System.ArtifactsDirectory)/Artifacts/$(modulesRepo)/${{ parameters.parametersFile }}' --what-if


      #Se ejecutaran las siguientes tareas cuando se use un microsoft-hosted agent pool
      - checkout: self
      - checkout: ModulesRepo

      - task: AzureCLI@2
        displayName: 'Desplegar resource group'
        condition: and(eq(variables['poolName'], ''), eq(variables['deployResourceGroup'], 'true'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account set --subscription '${{ parameters.subscriptionName }}'
            deploymentName='azureDeployment'$(date +"%d-%b-%Y")
            az deployment sub create -n $deploymentName -l $(location) --template-file '$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(modulesRepo)/${{ parameters.parametersFile }}' --what-if

      - task: AzureCLI@2
        displayName: 'Desplegar recurso'
        condition: and(eq(variables['poolName'], ''), eq(variables['deployResourceGroup'], 'false'))
        inputs:
          azureSubscription: $(subscriptionConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account set --subscription '${{ parameters.subscriptionName }}'
            deploymentName='azureDeployment'$(date +"%d-%b-%Y")
            az deployment group create -n $deploymentName -g '${{ parameters.resourceGroupName }}' --template-file '$(modulesRepo)/${{ parameters.templateFile }}' --parameters '$(modulesRepo)/${{ parameters.parametersFile }}' --what-if
